language: node_js
sudo: false
node_js:
  - '10'
  - '11'

cache:
  yarn: true
  timeout: 1000
  directories:
    - $HOME/.npm
    - 'node_modules'

before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn run lerna run prepublish

install:
  - yarn install

script:
  - yarn run test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

after_script:
  - 'cat packages/soldier/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'

deploy:
  provider: script
  script: 'yarn run lerna:publish'
  skip_cleanup: true
  on:
    node: '10'
    tags: true
