language: node_js
sudo: false

cache:
  timeout: 1000
  directories:
    - $HOME/.npm

before_install:
  - nvm install 10

install:
  - yarn install

script:
  - yarn run test

after_script: 'cat packages/soldier/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
